NAME        = so_long
LIBFT       = libft/libft.a
MLX         = mlx/libmlx.a
MLX_FLAGS   = -L mlx -lmlx -framework OpenGL -framework AppKit

CC          = cc
CFLAGS      = -Wall -Wextra -Werror -I inc -I libft/includes -I mlx
RM          = rm -f

SRC_DIR     = src
OBJ_DIR     = obj

SRCS        = \
    $(SRC_DIR)/main.c

OBJ         = $(SRCS:$(SRC_DIR)/%.c=$(OBJ_DIR)/%.o)

all: $(NAME) ascii

$(NAME): $(OBJ) $(LIBFT) $(MLX)
	@$(CC) $(CFLAGS) $(OBJ) $(LIBFT) $(MLX_FLAGS) -o $(NAME)

$(LIBFT):
	@make -C libft --silent

$(MLX):
	@make -C mlx --silent

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c $< -o $@

clean:
	@$(RM) -r $(OBJ_DIR)
	@make -C libft clean --silent
	@make -C mlx clean --silent

fclean: clean
	@$(RM) $(NAME)
	@make -C libft fclean --silent

re: fclean all

ascii:
	@echo "$(BOLD)$(PURPLE)"
	@if [ -f ascii_art.txt ]; then cat ascii_art.txt; fi
	@echo "$(END)"

.PHONY: all clean fclean re ascii